Repository depromeet/everyBody-iOS, pull requests merged in 2021-11, with the labels that each got.

#19 #12: add panorama album view
  everyBody/everyBody-iOS.xcodeproj/project.pbxproj
  everyBody/everyBody-iOS/Resource/Constants/Assets+Generated.swift
  everyBody/everyBody-iOS/Resource/Image.xcassets/Create.imageset/Contents.json
  everyBody/everyBody-iOS/Resource/Image.xcassets/Create.imageset/Create.png
  everyBody/everyBody-iOS/Resource/Image.xcassets/Create.imageset/Create@2x.png
  everyBody/everyBody-iOS/Resource/Image.xcassets/Create.imageset/Create@3x.png
  everyBody/everyBody-iOS/Resource/Image.xcassets/Share.imageset/Contents.json
  everyBody/everyBody-iOS/Resource/Image.xcassets/Share.imageset/Share.png
  everyBody/everyBody-iOS/Resource/Image.xcassets/Share.imageset/Share@2x.png
  everyBody/everyBody-iOS/Resource/Image.xcassets/Share.imageset/Share@3x.png
  everyBody/everyBody-iOS/Source/Extensions/UINavigationController+Extensions.swift
  everyBody/everyBody-iOS/Source/Panorama/Cells/AlbumCollectionViewCell.swift
  everyBody/everyBody-iOS/Source/Panorama/Cells/CellSample4.swift
  everyBody/everyBody-iOS/Source/Panorama/ViewControllers/AlbumViewController.swift
  everyBody/everyBody-iOS/Source/Panorama/ViewControllers/GridViewController.swift
  everyBody/everyBody-iOS/Source/Panorama/ViewControllers/PanoramaViewController.swift
  everyBody/everyBody-iOS/Source/Panorama/ViewControllers/ViewControllerSample4.swift
  everyBody/everyBody-iOS/Source/Panorama/ViewModels/PanoramaViewModel.swift
  everyBody/everyBody-iOS/Source/Panorama/ViewModels/ViewModelSample4.swift
  everyBody/everyBody-iOS/Source/Panorama/Views/ViewSample4.swift
Labels: 🎈 yukyung, 🏅 feat

#23 #22: 트래킹 되지 않는 파일 경로 수정
  everyBody/everyBody-iOS.xcodeproj/project.pbxproj
  everyBody/everyBody-iOS/Resource/Constants/Assets+Generated.swift
  everyBody/everyBody-iOS/Resource/Font/Gilroy-Bold.ttf
  everyBody/everyBody-iOS/Resource/Font/Gilroy-Light.ttf
  everyBody/everyBody-iOS/Resource/Font/Gilroy-Regular.ttf
  everyBody/everyBody-iOS/Resource/Font/Pretendard-Bold.ttf
  everyBody/everyBody-iOS/Resource/Font/Pretendard-Regular.ttf
  everyBody/everyBody-iOS/Resource/Font/Pretendard-SemiBold.ttf
  everyBody/everyBody-iOS/Source/Camera/Views/BottomSheetView.swift
  everyBody/everyBody-iOS/Source/Camera/Views/CaptureButton.swift
  everyBody/everyBody-iOS/Source/Camera/Views/CustomSwitch.swift
  everyBody/everyBody-iOS/Source/Camera/Views/NBBasicButton.swift
  everyBody/everyBody-iOS/Source/Camera/Views/NBSegmentedButton.swift
  everyBody/everyBody-iOS/Source/Camera/Views/NBSegmentedControl.swift
  everyBody/everyBody-iOS/Source/Camera/Views/TextWithIconView.swift
  everyBody/everyBody-iOS/Source/Camera/Views/ToastView.swift
Labels: 💪🏼 yezl, 🚨 bug

#25 #21: add Folder Selection VIew
  everyBody/.swiftlint.yml
  everyBody/everyBody-iOS.xcodeproj/project.pbxproj
  everyBody/everyBody-iOS/Resource/Constants/Assets+Generated.swift
  everyBody/everyBody-iOS/Resource/Font/Fonts.swift
  everyBody/everyBody-iOS/Resource/Image.xcassets/check.imageset/Contents.json
  everyBody/everyBody-iOS/Resource/Image.xcassets/check.imageset/check.png
  everyBody/everyBody-iOS/Resource/Image.xcassets/check.imageset/check@2x.png
  everyBody/everyBody-iOS/Resource/Image.xcassets/check.imageset/check@3x.png
  everyBody/everyBody-iOS/Resource/Image.xcassets/check_circle.imageset/Contents.json
  everyBody/everyBody-iOS/Resource/Image.xcassets/check_circle.imageset/check_circle.png
  everyBody/everyBody-iOS/Resource/Image.xcassets/check_circle.imageset/check_circle@2x.png
  everyBody/everyBody-iOS/Resource/Image.xcassets/check_circle.imageset/check_circle@3x.png
  everyBody/everyBody-iOS/Source/Base/BaseViewController.swift
  everyBody/everyBody-iOS/Source/Camera/Cells/FolderCollectionViewCell.swift
  everyBody/everyBody-iOS/Source/Camera/Cells/PoseCollectionViewCell.swift
  everyBody/everyBody-iOS/Source/Camera/Model/Album.swift
  everyBody/everyBody-iOS/Source/Camera/Model/Camera.swift
  everyBody/everyBody-iOS/Source/Camera/ViewControllers/CameraOutputViewController.swift
  everyBody/everyBody-iOS/Source/Camera/ViewControllers/CameraViewController.swift
  everyBody/everyBody-iOS/Source/Camera/ViewControllers/FolderSelectionViewController.swift
  everyBody/everyBody-iOS/Source/Camera/ViewModels/AlbumViewModel.swift
  everyBody/everyBody-iOS/Source/Camera/ViewModels/CameraViewModel.swift
  everyBody/everyBody-iOS/Source/Camera/ViewModels/PoseViewModel.swift
  everyBody/everyBody-iOS/Source/Camera/Views/BottomSheetView.swift
  everyBody/everyBody-iOS/Source/Camera/Views/CustomSwitch.swift
  everyBody/everyBody-iOS/Source/Component/NBBasicButton.swift
  everyBody/everyBody-iOS/Source/Component/NBSegmentedButton.swift
  everyBody/everyBody-iOS/Source/Component/NBSegmentedControl.swift
  everyBody/everyBody-iOS/Source/Component/NBTextField.swift
  everyBody/everyBody-iOS/Source/Component/SelectedView.swift
  everyBody/everyBody-iOS/Source/Extensions/UICollectionView+Generic.swift
  everyBody/everyBody-iOS/Source/Extensions/UIColor+Extension.swift
  everyBody/everyBody-iOS/Source/Extensions/UITextField+addLeftPadding.swift
  everyBody/everyBody-iOS/Source/Extensions/UIView+addShadow.swift
  everyBody/everyBody-iOS/Source/Extensions/UIView+addSubviews.swift
  everyBody/everyBody-iOS/Source/Extensions/UIViewController+hideKeyboard.swift
  everyBody/everyBody-iOS/Source/Extensions/className.swift
  everyBody/everyBody-iOS/Source/PopUp/PopUpViewController.swift
  everyBody/everyBody-iOS/Source/Protocol/PopUpActionDelegate.swift
Labels: 💪🏼 yezl, 🏅 feat

#26 #24: merge label to Image
  everyBody/everyBody-iOS.xcodeproj/project.pbxproj
  everyBody/everyBody-iOS/Source/Camera/ViewControllers/CameraOutputViewController.swift
  everyBody/everyBody-iOS/Source/Extensions/UIVIew+renderToImageView.swift
Labels: 💪🏼 yezl, 🏅 feat

#27 #17: add custom picker view
  everyBody/everyBody-iOS.xcodeproj/project.pbxproj
  everyBody/everyBody-iOS/Source/Camera/Model/AppDate.swift
  everyBody/everyBody-iOS/Source/Camera/Model/Camera.swift
  everyBody/everyBody-iOS/Source/Camera/ViewControllers/CameraOutputViewController.swift
  everyBody/everyBody-iOS/Source/Camera/ViewModels/CameraViewModel.swift
  everyBody/everyBody-iOS/Source/Camera/ViewModels/DateViewModel.swift
  everyBody/everyBody-iOS/Source/Camera/Views/NBDatePicker.swift
  everyBody/everyBody-iOS/Source/Extensions/String+2DigitFormat.swift
Labels: 💪🏼 yezl, 🏅 feat

#31 #28: add preferences view
  everyBody/everyBody-iOS.xcodeproj/project.pbxproj
  everyBody/everyBody-iOS.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  everyBody/everyBody-iOS/Resource/Constants/Assets+Generated.swift
  everyBody/everyBody-iOS/Resource/Font/Fonts.swift
  everyBody/everyBody-iOS/Resource/Image.xcassets/backwardsBack.imageset/Contents.json
  everyBody/everyBody-iOS/Resource/Image.xcassets/backwardsBack.imageset/backwardsBack.png
  everyBody/everyBody-iOS/Resource/Image.xcassets/backwardsBack.imageset/backwardsBack@2x.png
  everyBody/everyBody-iOS/Resource/Image.xcassets/backwardsBack.imageset/backwardsBack@3x.png
  everyBody/everyBody-iOS/Source/Base/BaseViewController.swift
  everyBody/everyBody-iOS/Source/Camera/ViewControllers/CameraViewController.swift
  everyBody/everyBody-iOS/Source/Camera/Views/CustomSwitch.swift
  everyBody/everyBody-iOS/Source/Component/NBDayButton.swift
  everyBody/everyBody-iOS/Source/Component/NBPrimaryButton.swift
  everyBody/everyBody-iOS/Source/Component/NBTextField.swift
  everyBody/everyBody-iOS/Source/Extensions/Rx+ViewWillAppear.swift
  everyBody/everyBody-iOS/Source/Extensions/UIImageView+setImage.swift
  everyBody/everyBody-iOS/Source/Extensions/UITableView+Generic.swift
  everyBody/everyBody-iOS/Source/Extensions/UITextField+attributedPlaceholder.swift
  everyBody/everyBody-iOS/Source/Extensions/UIVIew+renderToImageView.swift
  everyBody/everyBody-iOS/Source/Feed/Cells/CellSample3.swift
  everyBody/everyBody-iOS/Source/Feed/ViewControllers/ViewControllerSample3.swift
  everyBody/everyBody-iOS/Source/Feed/ViewModels/ViewModelSample3.swift
  everyBody/everyBody-iOS/Source/Feed/Views/ViewSample3.swift
  everyBody/everyBody-iOS/Source/Home/Cells/CellSample.swift
  everyBody/everyBody-iOS/Source/Home/Cells/ProfileTableViewCell.swift
  everyBody/everyBody-iOS/Source/Home/Data/PreferenceDataType.swift
  everyBody/everyBody-iOS/Source/Home/Model/UserInfo.swift
  everyBody/everyBody-iOS/Source/Home/Repository/PreferenceRepository.swift
  everyBody/everyBody-iOS/Source/Home/ViewControllers/PreferenceViewController.swift
  everyBody/everyBody-iOS/Source/Home/ViewControllers/PushSettingViewController.swift
  everyBody/everyBody-iOS/Source/Home/ViewControllers/ViewController.swift
  everyBody/everyBody-iOS/Source/Home/ViewModels/ProfileViewModel.swift
  everyBody/everyBody-iOS/Source/Home/ViewModels/ViewModelSample.swift
  everyBody/everyBody-iOS/Source/PopUp/PopUpViewController.swift
Labels: 💭 yezl, 🏅 feat

#32 #20: add grid + delete view
  everyBody/everyBody-iOS.xcodeproj/project.pbxproj
  everyBody/everyBody-iOS/Resource/Constants/Assets+Generated.swift
  everyBody/everyBody-iOS/Resource/Image.xcassets/clear.imageset/Contents.json
  everyBody/everyBody-iOS/Resource/Image.xcassets/clear.imageset/clear.png
  everyBody/everyBody-iOS/Resource/Image.xcassets/clear.imageset/clear@2x.png
  everyBody/everyBody-iOS/Resource/Image.xcassets/clear.imageset/clear@3x.png
  everyBody/everyBody-iOS/Resource/Image.xcassets/del.imageset/Contents.json
  everyBody/everyBody-iOS/Resource/Image.xcassets/del.imageset/del.png
  everyBody/everyBody-iOS/Resource/Image.xcassets/del.imageset/del@2x.png
  everyBody/everyBody-iOS/Resource/Image.xcassets/del.imageset/del@3x.png
  everyBody/everyBody-iOS/Resource/Image.xcassets/photo_camera.imageset/Contents.json
  everyBody/everyBody-iOS/Resource/Image.xcassets/photo_camera.imageset/photo_camera.png
  everyBody/everyBody-iOS/Resource/Image.xcassets/photo_camera.imageset/photo_camera@2x.png
  everyBody/everyBody-iOS/Resource/Image.xcassets/photo_camera.imageset/photo_camera@3x.png
  everyBody/everyBody-iOS/Source/Component/SelectedView.swift
  everyBody/everyBody-iOS/Source/Extensions/UINavigationController+Extensions.swift
  everyBody/everyBody-iOS/Source/Extensions/UINavigationItem+Extensions.swift
  everyBody/everyBody-iOS/Source/Panorama/Cells/BottomCollectionViewCell.swift
  everyBody/everyBody-iOS/Source/Panorama/Cells/CameraCollectionViewCell.swift
  everyBody/everyBody-iOS/Source/Panorama/Cells/TopCollectionViewCell.swift
  everyBody/everyBody-iOS/Source/Panorama/Extensions/PanoramaViewController+Extensions.swift
  everyBody/everyBody-iOS/Source/Panorama/ViewControllers/AlbumViewController.swift
  everyBody/everyBody-iOS/Source/Panorama/ViewControllers/GridViewController.swift
  everyBody/everyBody-iOS/Source/Panorama/ViewControllers/PanoramaViewController.swift
  everyBody/everyBody-iOS/Source/Panorama/ViewModels/PanoramaViewModel.swift
Labels: 🎈 yukyung, 🏅 feat

#34 #33: refactor navigationbar
  everyBody/everyBody-iOS.xcodeproj/project.pbxproj
  everyBody/everyBody-iOS/Resource/Constants/Assets+Generated.swift
  everyBody/everyBody-iOS/Resource/Support/SceneDelegate.swift
  everyBody/everyBody-iOS/Source/Camera/ViewControllers/CameraViewController.swift
  everyBody/everyBody-iOS/Source/Extensions/UINavigationController+Extensions.swift
  everyBody/everyBody-iOS/Source/Extensions/UINavigationItem+Extensions.swift
  everyBody/everyBody-iOS/Source/Home/ViewControllers/HomeViewController.swift
  everyBody/everyBody-iOS/Source/Panorama/ViewControllers/PanoramaViewController.swift
Labels: 💭 yezl, ✏️ refactor

#36 #35: add folder creation view
  everyBody/everyBody-iOS.xcodeproj/project.pbxproj
  everyBody/everyBody-iOS/Resource/Font/Fonts.swift
  everyBody/everyBody-iOS/Source/Base/BaseViewController.swift
  everyBody/everyBody-iOS/Source/Component/NBPrimaryButton.swift
  everyBody/everyBody-iOS/Source/Extensions/UIViewController+hideKeyboard.swift
  everyBody/everyBody-iOS/Source/Home/ViewControllers/FolderCreationViewController.swift
  everyBody/everyBody-iOS/Source/Home/ViewControllers/HomeViewController.swift
  everyBody/everyBody-iOS/Source/PopUp/PopUpViewController.swift
Labels: 💭 yezl, 🏅 feat

#38 #20 : update panorama view + add delete popup
  everyBody/everyBody-iOS/Source/Panorama/Cells/BottomCollectionViewCell.swift
  everyBody/everyBody-iOS/Source/Panorama/Cells/CameraCollectionViewCell.swift
  everyBody/everyBody-iOS/Source/Panorama/Cells/TopCollectionViewCell.swift
  everyBody/everyBody-iOS/Source/Panorama/Extensions/PanoramaViewController+Extensions.swift
  everyBody/everyBody-iOS/Source/Panorama/ViewControllers/PanoramaViewController.swift
  everyBody/everyBody-iOS/Source/Panorama/ViewModels/PanoramaViewModel.swift
Labels: 🎈 yukyung, ✏️ refactor

#40 #39: add album view
  everyBody/everyBody-iOS.xcodeproj/project.pbxproj
  everyBody/everyBody-iOS/Source/Camera/ViewControllers/FolderSelectionViewController.swift
  everyBody/everyBody-iOS/Source/Component/AlbumCollectionViewCell.swift
  everyBody/everyBody-iOS/Source/Home/ViewControllers/HomeViewController.swift
  everyBody/everyBody-iOS/Source/Panorama/ViewControllers/PanoramaViewController.swift
Labels: 🎈 yukyung, 🏅 feat

#41 #37: 서버 연결 베이스 셋팅 및 프로필뷰 서버 연결
  .gitignore
  everyBody/everyBody-iOS.xcodeproj/project.pbxproj
  everyBody/everyBody-iOS.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  everyBody/everyBody-iOS/Resource/Support/Info.plist
  everyBody/everyBody-iOS/Source/Home/Cells/ProfileTableViewCell.swift
  everyBody/everyBody-iOS/Source/Home/Data/ProfileDataType.swift
  everyBody/everyBody-iOS/Source/Home/Model/UserInfo.swift
  everyBody/everyBody-iOS/Source/Home/Repository/PreferenceRepository.swift
  everyBody/everyBody-iOS/Source/Home/Repository/ProfileRepository.swift
  everyBody/everyBody-iOS/Source/Home/UseCase/ProfileUseCase.swift
  everyBody/everyBody-iOS/Source/Home/ViewControllers/HomeViewController.swift
  everyBody/everyBody-iOS/Source/Home/ViewControllers/ProfileViewController.swift
  everyBody/everyBody-iOS/Source/Home/ViewModels/ProfileViewModel.swift
  everyBody/everyBody-iOS/Source/Network/Base/BaseTargetType.swift
  everyBody/everyBody-iOS/Source/Network/Base/HTTPMethodURL.swift
  everyBody/everyBody-iOS/Source/Network/Base/MultiMoyaProvider.swift
  everyBody/everyBody-iOS/Source/Network/MyPage/MyPageAPI.swift
  everyBody/everyBody-iOS/Source/Network/MyPage/MyPageService.swift
  everyBody/everyBody-iOS/Source/Network/Request/ProfileRequestModel.swift
Labels: 💭 yezl, 🏅 feat
