Repository depromeet/everyBody-iOS, pull requests merged in 2021-12, with the labels that each got.

#46 #43: 앨범 생성 뷰 서버 연결
  everyBody/everyBody-iOS.xcodeproj/project.pbxproj
  everyBody/everyBody-iOS/Resource/Support/SceneDelegate.swift
  everyBody/everyBody-iOS/Source/Base/BaseViewController.swift
  everyBody/everyBody-iOS/Source/Camera/ViewControllers/CameraOutputViewController.swift
  everyBody/everyBody-iOS/Source/Camera/ViewControllers/CameraViewController.swift
  everyBody/everyBody-iOS/Source/Camera/ViewControllers/FolderSelectionViewController.swift
  everyBody/everyBody-iOS/Source/Component/NBSegmentedControl.swift
  everyBody/everyBody-iOS/Source/Extensions/UINavigationController+Extensions.swift
  everyBody/everyBody-iOS/Source/Home/Repository/AlbumRepository.swift
  everyBody/everyBody-iOS/Source/Home/UseCase/AlbumUseCase.swift
  everyBody/everyBody-iOS/Source/Home/ViewControllers/AlbumCreationViewController.swift
  everyBody/everyBody-iOS/Source/Home/ViewControllers/HomeViewController.swift
  everyBody/everyBody-iOS/Source/Home/ViewModels/AlbumCreationViewModel.swift
  everyBody/everyBody-iOS/Source/Network/Base/HTTPMethodURL.swift
  everyBody/everyBody-iOS/Source/Network/CreateAlbum/CreateAlbumAPI.swift
  everyBody/everyBody-iOS/Source/Network/CreateAlbum/CreateAlbumService.swift
  everyBody/everyBody-iOS/Source/Network/Request/CreateAlbumRequestModel.swift
  everyBody/everyBody-iOS/Source/Panorama/ViewControllers/PanoramaViewController.swift
  everyBody/everyBody-iOS/Source/PopUp/PopUpViewController.swift
Labels: 💭 yezl, 🏅 feat

#48 #42: album list server
  everyBody/everyBody-iOS.xcodeproj/project.pbxproj
  everyBody/everyBody-iOS.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  everyBody/everyBody-iOS/Source/Camera/Model/Album.swift
  everyBody/everyBody-iOS/Source/Camera/ViewControllers/FolderSelectionViewController.swift
  everyBody/everyBody-iOS/Source/Camera/ViewModels/AlbumDummy.swift
  everyBody/everyBody-iOS/Source/Camera/ViewModels/AlbumViewModel.swift
  everyBody/everyBody-iOS/Source/Component/AlbumCollectionViewCell.swift
  everyBody/everyBody-iOS/Source/Home/Repository/AlbumRepository.swift
  everyBody/everyBody-iOS/Source/Home/UseCase/AlbumUseCase.swift
  everyBody/everyBody-iOS/Source/Home/ViewControllers/HomeViewController.swift
  everyBody/everyBody-iOS/Source/Network/Album/AlbumAPI.swift
  everyBody/everyBody-iOS/Source/Network/Album/AlbumService.swift
  everyBody/everyBody-iOS/Source/Network/Base/HTTPMethodURL.swift
Labels: 🎈 yukyung, 🏅 feat

#52 #51: 오타 수정
  everyBody/everyBody-iOS/Source/Camera/ViewControllers/FolderSelectionViewController.swift
Labels: 🎈 yukyung, 🚨 bug

#53 #45: 푸시 알림 환경설정 뷰 서버 연결
  everyBody/everyBody-iOS.xcodeproj/project.pbxproj
  everyBody/everyBody-iOS/Source/Home/Model/NotificationConfig.swift
  everyBody/everyBody-iOS/Source/Home/Repository/ProfileRepository.swift
  everyBody/everyBody-iOS/Source/Home/UseCase/ProfileUseCase.swift
  everyBody/everyBody-iOS/Source/Home/ViewControllers/PushSettingViewController.swift
  everyBody/everyBody-iOS/Source/Home/ViewModels/NotificationViewModel.swift
  everyBody/everyBody-iOS/Source/Network/Base/HTTPMethodURL.swift
  everyBody/everyBody-iOS/Source/Network/MoyaLoggingPlugin.swift
  everyBody/everyBody-iOS/Source/Network/Notification/NotificationAPI.swift
  everyBody/everyBody-iOS/Source/Network/Notification/NotificationService.swift
  everyBody/everyBody-iOS/Source/PopUp/PopUpViewController.swift
Labels: 💭 yezl

#54 #50: 파노라마 앨범 조회 서버 연결
  everyBody/everyBody-iOS/Source/Component/AlbumCollectionViewCell.swift
  everyBody/everyBody-iOS/Source/Home/ViewControllers/HomeViewController.swift
  everyBody/everyBody-iOS/Source/Panorama/Cells/BottomCollectionViewCell.swift
  everyBody/everyBody-iOS/Source/Panorama/Cells/TopCollectionViewCell.swift
  everyBody/everyBody-iOS/Source/Panorama/Extensions/PanoramaViewController+Extensions.swift
  everyBody/everyBody-iOS/Source/Panorama/ViewControllers/PanoramaViewController.swift
Labels: 🎈 yukyung, 🏅 feat

#57 #44: 카메라 뷰 서버 연결
  everyBody/everyBody-iOS.xcodeproj/project.pbxproj
  everyBody/everyBody-iOS/Source/Camera/Model/CameraRequestManager.swift
  everyBody/everyBody-iOS/Source/Camera/Repository/CameraRepository.swift
  everyBody/everyBody-iOS/Source/Camera/UseCase/CameraUseCase.swift
  everyBody/everyBody-iOS/Source/Camera/ViewControllers/AlbumSelectionViewController.swift
  everyBody/everyBody-iOS/Source/Camera/ViewControllers/CameraOutputViewController.swift
  everyBody/everyBody-iOS/Source/Camera/ViewControllers/FolderSelectionViewController.swift
  everyBody/everyBody-iOS/Source/Camera/ViewModels/AlbumDummy.swift
  everyBody/everyBody-iOS/Source/Camera/ViewModels/AlbumSelectionViewModel.swift
  everyBody/everyBody-iOS/Source/Camera/ViewModels/AlbumViewModel.swift
  everyBody/everyBody-iOS/Source/Component/AlbumCollectionViewCell.swift
  everyBody/everyBody-iOS/Source/Component/NBSegmentedControl.swift
  everyBody/everyBody-iOS/Source/Home/Repository/AlbumRepository.swift
  everyBody/everyBody-iOS/Source/Home/UseCase/AlbumUseCase.swift
  everyBody/everyBody-iOS/Source/Network/Album/AlbumService.swift
  everyBody/everyBody-iOS/Source/Network/Base/HTTPMethodURL.swift
  everyBody/everyBody-iOS/Source/Network/Camera/CameraAPI.swift
  everyBody/everyBody-iOS/Source/Network/Camera/CameraService.swift
  everyBody/everyBody-iOS/Source/Network/CreateAlbum/CreateAlbumAPI.swift
  everyBody/everyBody-iOS/Source/Network/CreateAlbum/CreateAlbumService.swift
  everyBody/everyBody-iOS/Source/Network/Request/PhotoRequestModel.swift
  everyBody/everyBody-iOS/Source/PopUp/PopUpViewController.swift
Labels: 💭 yezl, 🏅 feat

#60 #55: 공통 토스트 생성 및 연결
  Noonbody/Noonbody.xcodeproj/project.pbxproj
  Noonbody/Noonbody/Resource/Support/AppDelegate.swift
  Noonbody/Noonbody/Resource/Support/SceneDelegate.swift
  Noonbody/Noonbody/Source/Component/ToastView.swift
  Noonbody/Noonbody/Source/Extensions/UIViewController+ToastView.swift
  Noonbody/Noonbody/Source/Scene/Base/BaseViewController.swift
  Noonbody/Noonbody/Source/Scene/Camera/Cells/PoseCollectionViewCell.swift
  Noonbody/Noonbody/Source/Scene/Camera/Model/Album.swift
  Noonbody/Noonbody/Source/Scene/Camera/Model/AppDate.swift
  Noonbody/Noonbody/Source/Scene/Camera/Model/Camera.swift
  Noonbody/Noonbody/Source/Scene/Camera/Model/CameraRequestManager.swift
  Noonbody/Noonbody/Source/Scene/Camera/Model/Pose.swift
  Noonbody/Noonbody/Source/Scene/Camera/Model/ViewFinder.swift
  Noonbody/Noonbody/Source/Scene/Camera/Repository/CameraRepository.swift
  Noonbody/Noonbody/Source/Scene/Camera/UseCase/CameraUseCase.swift
  Noonbody/Noonbody/Source/Scene/Camera/ViewControllers/AlbumSelectionViewController.swift
  Noonbody/Noonbody/Source/Scene/Camera/ViewControllers/CameraOutputViewController.swift
  Noonbody/Noonbody/Source/Scene/Camera/ViewControllers/CameraViewController.swift
  Noonbody/Noonbody/Source/Scene/Camera/ViewModels/AlbumSelectionViewModel.swift
  Noonbody/Noonbody/Source/Scene/Camera/ViewModels/AlbumViewModel.swift
  Noonbody/Noonbody/Source/Scene/Camera/ViewModels/CameraViewModel.swift
  Noonbody/Noonbody/Source/Scene/Camera/ViewModels/DateViewModel.swift
  Noonbody/Noonbody/Source/Scene/Camera/ViewModels/PoseViewModel.swift
  Noonbody/Noonbody/Source/Scene/Camera/Views/BottomSheetView.swift
  Noonbody/Noonbody/Source/Scene/Camera/Views/CustomSwitch.swift
  Noonbody/Noonbody/Source/Scene/Camera/Views/GuideView.swift
  Noonbody/Noonbody/Source/Scene/Camera/Views/NBDatePicker.swift
  Noonbody/Noonbody/Source/Scene/Camera/Views/TextWithIconView.swift
  Noonbody/Noonbody/Source/Scene/Home/Cells/ProfileTableViewCell.swift
  Noonbody/Noonbody/Source/Scene/Home/Data/ProfileDataType.swift
  Noonbody/Noonbody/Source/Scene/Home/Model/NotificationConfig.swift
  Noonbody/Noonbody/Source/Scene/Home/Model/UserInfo.swift
  Noonbody/Noonbody/Source/Scene/Home/Repository/AlbumRepository.swift
  Noonbody/Noonbody/Source/Scene/Home/Repository/ProfileRepository.swift
  Noonbody/Noonbody/Source/Scene/Home/UseCase/AlbumUseCase.swift
  Noonbody/Noonbody/Source/Scene/Home/UseCase/ProfileUseCase.swift
  Noonbody/Noonbody/Source/Scene/Home/ViewControllers/AlbumCreationViewController.swift
  Noonbody/Noonbody/Source/Scene/Home/ViewControllers/HomeViewController.swift
  Noonbody/Noonbody/Source/Scene/Home/ViewControllers/ProfileViewController.swift
  Noonbody/Noonbody/Source/Scene/Home/ViewControllers/PushSettingViewController.swift
  Noonbody/Noonbody/Source/Scene/Home/ViewModels/AlbumCreationViewModel.swift
  Noonbody/Noonbody/Source/Scene/Home/ViewModels/NotificationViewModel.swift
  Noonbody/Noonbody/Source/Scene/Home/ViewModels/ProfileViewModel.swift
  Noonbody/Noonbody/Source/Scene/Home/Views/ViewSample.swift
  Noonbody/Noonbody/Source/Scene/Panorama/Cells/BottomCollectionViewCell.swift
  Noonbody/Noonbody/Source/Scene/Panorama/Cells/CameraCollectionViewCell.swift
  Noonbody/Noonbody/Source/Scene/Panorama/Cells/TopCollectionViewCell.swift
  Noonbody/Noonbody/Source/Scene/Panorama/Extensions/PanoramaViewController+Extensions.swift
  Noonbody/Noonbody/Source/Scene/Panorama/ViewControllers/PanoramaViewController.swift
  Noonbody/Noonbody/Source/Scene/Panorama/ViewModels/PanoramaViewModel.swift
  Noonbody/Noonbody/Source/Scene/PopUp/PopUpViewController.swift
Labels: 💭 yezl, 🏅 feat

#61 #29: firebase push notification setting
  .gitignore
  Noonbody/Noonbody.xcodeproj/project.pbxproj
  Noonbody/Noonbody.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Noonbody/Noonbody/Noonbody.entitlements
  Noonbody/Noonbody/Resource/Support/AppDelegate.swift
  Noonbody/Noonbody/Resource/Support/Info.plist
Labels: 💭 yezl, 🏅 feat

#62 #47 : 파노마라뷰 SE2 대응, 레이아웃 에러 픽스
  Noonbody/Noonbody.xcodeproj/project.pbxproj
  Noonbody/Noonbody/Source/Scene/Panorama/Cells/BottomCollectionViewCell.swift
  Noonbody/Noonbody/Source/Scene/Panorama/Cells/TopCollectionViewCell.swift
  Noonbody/Noonbody/Source/Scene/Panorama/Extensions/PanoramaViewController+Extensions.swift
  Noonbody/Noonbody/Source/Scene/Panorama/ViewControllers/PanoramaViewController.swift
Labels: 🎈 yukyung, 🚨 bug

#64 #30: 런치 스크린 회원가입 / 로그인 플로우
  Noonbody/Noonbody.xcodeproj/project.pbxproj
  Noonbody/Noonbody/Resource/Constants/Assets+Generated.swift
  Noonbody/Noonbody/Resource/Image.xcassets/Logo.imageset/Contents.json
  Noonbody/Noonbody/Resource/Image.xcassets/Logo.imageset/Logo.png
  Noonbody/Noonbody/Resource/Image.xcassets/Logo.imageset/Logo@2x.png
  Noonbody/Noonbody/Resource/Image.xcassets/Logo.imageset/Logo@3x.png
  Noonbody/Noonbody/Resource/LaunchScreen.storyboard
  Noonbody/Noonbody/Resource/Support/AppDelegate.swift
  Noonbody/Noonbody/Resource/Support/Info.plist
  Noonbody/Noonbody/Resource/Support/SceneDelegate.swift
  Noonbody/Noonbody/Source/Extensions/UIImage+resizeImage.swift
  Noonbody/Noonbody/Source/Network/Auth/AuthAPI.swift
  Noonbody/Noonbody/Source/Network/Auth/AuthService.swift
  Noonbody/Noonbody/Source/Network/Base/BaseTargetType.swift
  Noonbody/Noonbody/Source/Network/Base/HTTPMethodURL.swift
  Noonbody/Noonbody/Source/Network/Base/MoyaLoggingPlugin.swift
  Noonbody/Noonbody/Source/Network/Base/MultiMoyaProvider.swift
  Noonbody/Noonbody/Source/Network/Request/SignInRequestModel.swift
  Noonbody/Noonbody/Source/Network/Request/SignUpRequestModel.swift
  Noonbody/Noonbody/Source/Scene/Home/ViewControllers/HomeViewController.swift
  Noonbody/Noonbody/Source/Scene/Home/ViewControllers/ProfileViewController.swift
  Noonbody/Noonbody/Source/Scene/Home/ViewModels/ProfileViewModel.swift
  Noonbody/Noonbody/Source/Scene/Launch/LaunchService.swift
  Noonbody/Noonbody/Source/Scene/Launch/Model/SignInResponse.swift
  Noonbody/Noonbody/Source/Scene/Launch/ViewController/LaunchScreenViewController.swift
Labels: 💭 yezl, 🏅 feat

#66 #63: delete photo server
  Noonbody/Noonbody.xcodeproj/project.pbxproj
  Noonbody/Noonbody/Source/Component/AlbumEmptyView.swift
  Noonbody/Noonbody/Source/Network/Album/AlbumAPI.swift
  Noonbody/Noonbody/Source/Network/Album/AlbumService.swift
  Noonbody/Noonbody/Source/Network/Base/HTTPMethodURL.swift
  Noonbody/Noonbody/Source/Scene/Camera/Model/Album.swift
  Noonbody/Noonbody/Source/Scene/Home/Repository/AlbumRepository.swift
  Noonbody/Noonbody/Source/Scene/Home/UseCase/AlbumUseCase.swift
  Noonbody/Noonbody/Source/Scene/Home/ViewControllers/HomeViewController.swift
  Noonbody/Noonbody/Source/Scene/Panorama/Cells/BottomCollectionViewCell.swift
  Noonbody/Noonbody/Source/Scene/Panorama/Cells/CameraCollectionViewCell.swift
  Noonbody/Noonbody/Source/Scene/Panorama/Cells/TopCollectionViewCell.swift
  Noonbody/Noonbody/Source/Scene/Panorama/Extensions/PanoramaViewController+Extensions.swift
  Noonbody/Noonbody/Source/Scene/Panorama/ViewControllers/PanoramaViewController.swift
Labels: 🎈 yukyung, 🏅 feat

#69 #68: 홈 화면 리스트 셀 및 Empty View
  Noonbody/Noonbody.xcodeproj/project.pbxproj
  Noonbody/Noonbody/Resource/Constants/Assets+Generated.swift
  Noonbody/Noonbody/Resource/Image.xcassets/Empty.imageset/Contents.json
  Noonbody/Noonbody/Resource/Image.xcassets/Empty.imageset/Empty.png
  Noonbody/Noonbody/Resource/Image.xcassets/Empty.imageset/Empty@2x.png
  Noonbody/Noonbody/Resource/Image.xcassets/Empty.imageset/Empty@3x.png
  Noonbody/Noonbody/Resource/Image.xcassets/Empty2.imageset/Contents.json
  Noonbody/Noonbody/Resource/Image.xcassets/Empty2.imageset/Empty2.png
  Noonbody/Noonbody/Resource/Image.xcassets/Empty2.imageset/Empty2@2x.png
  Noonbody/Noonbody/Resource/Image.xcassets/Empty2.imageset/Empty2@3x.png
  Noonbody/Noonbody/Resource/Image.xcassets/ListGradation.imageset/Contents.json
  Noonbody/Noonbody/Resource/Image.xcassets/ListGradation.imageset/List.png
  Noonbody/Noonbody/Resource/Image.xcassets/ListGradation.imageset/List@2x.png
  Noonbody/Noonbody/Resource/Image.xcassets/ListGradation.imageset/List@3x.png
  Noonbody/Noonbody/Source/Component/AlbumCollectionViewCell.swift
  Noonbody/Noonbody/Source/Extensions/UIImage+resizeImage.swift
  Noonbody/Noonbody/Source/Extensions/UINavigationController+Extensions.swift
  Noonbody/Noonbody/Source/Scene/Home/Cells/ListCollectionViewCell.swift
  Noonbody/Noonbody/Source/Scene/Home/ViewControllers/HomeViewController.swift
Labels: 💭 yezl, 🏅 feat

#71 #70: 가로 모드 및 다크 모드 제한
  Noonbody/Noonbody/Resource/Support/AppDelegate.swift
  Noonbody/Noonbody/Resource/Support/Info.plist
Labels: 💭 yezl, 🏅 feat
