Repository depromeet/everyBody-iOS, pull requests merged in 2022-02, with the labels that each got.

#139 [NON_ISSUE] v1.0.3을 위한 자잘한 코드 수정
  Noonbody/Noonbody.xcodeproj/project.pbxproj
  Noonbody/Noonbody/Resource/Constants/Assets+Generated.swift
  Noonbody/Noonbody/Resource/Image.xcassets/M_Upper2.imageset/Contents.json
  Noonbody/Noonbody/Resource/Image.xcassets/M_Upper2.imageset/W_Upper2.png
  Noonbody/Noonbody/Resource/Image.xcassets/M_Upper2.imageset/W_Upper2@2x.png
  Noonbody/Noonbody/Resource/Image.xcassets/M_Upper2.imageset/W_Upper2@3x.png
  Noonbody/Noonbody/Resource/Image.xcassets/manUpper2.imageset/Contents.json
  Noonbody/Noonbody/Resource/Image.xcassets/manUpper2.imageset/manWhole2.png
  Noonbody/Noonbody/Resource/Image.xcassets/manUpper2.imageset/manWhole2@2x.png
  Noonbody/Noonbody/Resource/Image.xcassets/manUpper2.imageset/manWhole2@3x.png
  Noonbody/Noonbody/Resource/Support/Info.plist
  Noonbody/Noonbody/Source/Presentation/Camera/ViewControllers/CameraViewController.swift
  Noonbody/Noonbody/Source/Presentation/Camera/ViewModels/CameraViewModel.swift
  Noonbody/Noonbody/Source/Presentation/Home/ViewControllers/AlbumCreationViewController.swift
  Noonbody/Noonbody/Source/Presentation/Launch/ViewController/LaunchScreenViewController.swift
  Noonbody/Noonbody/Source/Presentation/Utils/PopUpViewController.swift
Labels: 🧸 chore

#144 #143: 빌드 환경 분리 및 런치 로직 변경
  Noonbody/Noonbody.xcodeproj/project.pbxproj
  Noonbody/Noonbody.xcodeproj/xcshareddata/xcschemes/Noonbody.xcscheme
  Noonbody/Noonbody/Resource/Support/Info.plist
  Noonbody/Noonbody/Source/Presentation/Launch/ViewController/LaunchScreenViewController.swift
Labels: 💭 yezl, 🧸 chore

#142 #140: 부위별 탭에만 사진이 있을 경우, 해당 탭 디폴트로 노출
  Noonbody/Noonbody.xcodeproj/project.pbxproj
  Noonbody/Noonbody/Source/Presentation/Panorama/ViewControllers/PanoramaViewController+Extensions.swift
  Noonbody/Noonbody/Source/Presentation/Panorama/ViewControllers/PanoramaViewController.swift
Labels: 🎈 yukyung, 🚨 bug

#146 #143: 사진 추가 시 맨 처음에 추가 되도록 변경
  Noonbody/Noonbody/Source/Presentation/Camera/ViewControllers/AlbumSelectionViewController.swift
Labels: 💭 yezl, 🚨 bug

#147 #138: 탭 분류가 제대로 안되는 현상 수정
  Noonbody/Noonbody/Source/Presentation/Camera/ViewControllers/CameraOutputViewController.swift
Labels: 💭 yezl, 🚨 bug

#148 #141: iOS14에서 디폴트 셀이 셀렉트되지 않는 버그, empty view가 hidden되지 않는 버그 픽스
  Noonbody/Noonbody.xcodeproj/project.pbxproj
  Noonbody/Noonbody/Source/Presentation/Panorama/ViewControllers/PanoramaViewController.swift
Labels: 🎈 yukyung, 🚨 bug
