Repository depromeet/everyBody-iOS, pull requests merged in 2022-06, with the labels that each got.

#167 #166: 동영상 저장 뷰 로컬 마이그레이션
  Noonbody/.swiftlint.yml
  Noonbody/Noonbody.xcodeproj/project.pbxproj
  Noonbody/Noonbody.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Noonbody/Noonbody/Source/Presentation/Component/AlbumCollectionViewCell.swift
  Noonbody/Noonbody/Source/Presentation/Home/Cells/ListCollectionViewCell.swift
  Noonbody/Noonbody/Source/Presentation/Panorama/Cells/BottomCollectionViewCell.swift
  Noonbody/Noonbody/Source/Presentation/Panorama/Cells/TopCollectionViewCell.swift
  Noonbody/Noonbody/Source/Presentation/Panorama/ViewControllers/PanoramaViewController.swift
  Noonbody/Noonbody/Source/Presentation/Utils/AlbumManager.swift
  Noonbody/Noonbody/Source/Presentation/Utils/PopUpViewController.swift
  Noonbody/Noonbody/Source/Presentation/Utils/Rx+PreviewCollectionViewCell.swift
  Noonbody/Noonbody/Source/Presentation/Video/Cell/PreviewCollectionViewCell.swift
  Noonbody/Noonbody/Source/Presentation/Video/ViewController/VideoEditViewController.swift
  Noonbody/Noonbody/Source/Presentation/Video/ViewController/VideoGenerator.swift
  Noonbody/Noonbody/Source/Presentation/Video/ViewModel/VideoViewModel.swift
Labels: 💭 yezl, 🏅 feat

#168 feat: 마이그레이션 서버 연결
  Noonbody/Noonbody.xcodeproj/project.pbxproj
  Noonbody/Noonbody/Source/Data/Network/MoyaService/MyPage/MyPageAPI.swift
  Noonbody/Noonbody/Source/Data/Network/MoyaService/MyPage/MyPageService.swift
  Noonbody/Noonbody/Source/Data/Network/MoyaService/Utils/HTTPMethodURL.swift
  Noonbody/Noonbody/Source/Data/Network/Repositories/DefaultPictureRepository.swift
  Noonbody/Noonbody/Source/Data/Network/Repositories/DefaultPreferenceRepository.swift
  Noonbody/Noonbody/Source/Data/Realm/RealmService/RealmMigrationService.swift
  Noonbody/Noonbody/Source/Domain/Entity/UserInfo.swift
  Noonbody/Noonbody/Source/Presentation/Launch/ViewController/LaunchScreenViewController.swift
Labels: 🎈 yukyung, 🏅 feat

#169 #165: imagePath 오류로 앨범 이미지가 뜨지않는 에러 fix
  Noonbody/Noonbody/Source/Data/Realm/RealmService/RealmMigrationService.swift
  Noonbody/Noonbody/Source/Presentation/Launch/ViewController/LaunchScreenViewController.swift
Labels: 🎈 yukyung, 🏅 feat, 🚨 bug
