Repository depromeet/everyBody-iOS, pull requests merged in 2022-09, with the labels that each got.

#181 #179: background에서 foreground 진입시 생체인증 추가, 잠금해제 팝업 로직 수정
  Noonbody/Noonbody/Resource/Support/SceneDelegate.swift
  Noonbody/Noonbody/Source/Presentation/Launch/ViewController/LaunchScreenViewController.swift
  Noonbody/Noonbody/Source/Presentation/Preferences/Cells/ProfileTableViewCell.swift
  Noonbody/Noonbody/Source/Presentation/Preferences/ViewControllers/AuthenticationPopupViewController.swift
Labels: 🫧 yukyung, 🚨 bug

#183 #182: add spm package
  Noonbody/Noonbody.xcodeproj/project.pbxproj
  Noonbody/Noonbody.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
Labels: 💭 yezl, 🏅 feat

#186 #182: 믹스패널 초기 설정
  .gitignore
  Noonbody/Noonbody/Resource/Config.xcconfig
  Noonbody/Noonbody/Resource/Support/AppDelegate.swift
  Noonbody/Noonbody/Resource/Support/Info.plist
Labels: 💭 yezl, 🏅 feat

#187 #184: 파노라마, 홈 뷰 믹스패널 추가
  Noonbody/Noonbody.xcodeproj/project.pbxproj
  Noonbody/Noonbody/Source/Presentation/Camera/ViewControllers/AlbumSelectionViewController.swift
  Noonbody/Noonbody/Source/Presentation/Home/ViewControllers/HomeViewController.swift
  Noonbody/Noonbody/Source/Presentation/Panorama/ViewControllers/PanoramaViewController.swift
  Noonbody/Noonbody/Source/Presentation/Utils/UINavigationController+Extensions.swift
Labels: 🫧 yukyung, 🏅 feat

#188 #185: add user event tracking
  Noonbody/Noonbody.xcodeproj/project.pbxproj
  Noonbody/Noonbody/Resource/Support/AppDelegate.swift
  Noonbody/Noonbody/Resource/Support/SceneDelegate.swift
  Noonbody/Noonbody/Source/Presentation/Base/BaseViewController.swift
  Noonbody/Noonbody/Source/Presentation/Camera/ViewControllers/AlbumSelectionViewController.swift
  Noonbody/Noonbody/Source/Presentation/Camera/ViewControllers/CameraOutputViewController.swift
  Noonbody/Noonbody/Source/Presentation/Camera/ViewControllers/CameraViewController.swift
  Noonbody/Noonbody/Source/Presentation/Camera/ViewModels/AlbumSelectionViewModel.swift
  Noonbody/Noonbody/Source/Presentation/Camera/Views/BottomSheetView.swift
  Noonbody/Noonbody/Source/Presentation/Panorama/ViewControllers/PanoramaViewController.swift
  Noonbody/Noonbody/Source/Presentation/Preferences/Cells/ProfileTableViewCell.swift
  Noonbody/Noonbody/Source/Presentation/Preferences/ViewControllers/MottoViewController.swift
  Noonbody/Noonbody/Source/Presentation/Preferences/ViewControllers/ProfileViewController.swift
  Noonbody/Noonbody/Source/Presentation/Utils/Environment.swift
  Noonbody/Noonbody/Source/Presentation/Video/ViewController/VideoEditViewController.swift
  Noonbody/Noonbody/Source/Presentation/Video/ViewModel/VideoViewModel.swift
Labels: 💭 yezl

#190 #189: 런치 스크린 로직 수정
  Noonbody/Noonbody.xcodeproj/project.pbxproj
  Noonbody/Noonbody/Resource/Constants/UserDefaultKey.swift
  Noonbody/Noonbody/Resource/Support/AppDelegate.swift
  Noonbody/Noonbody/Resource/Support/SceneDelegate.swift
  Noonbody/Noonbody/Source/Data/Network/MoyaService/Album/AlbumAPI.swift
  Noonbody/Noonbody/Source/Data/Network/MoyaService/Utils/BaseTargetType.swift
  Noonbody/Noonbody/Source/Presentation/Home/ViewControllers/HomeViewController.swift
  Noonbody/Noonbody/Source/Presentation/Launch/ViewController/LaunchScreenViewController.swift
  Noonbody/Noonbody/Source/Presentation/Preferences/BiometricsAuth.swift
  Noonbody/Noonbody/Source/Presentation/Preferences/Cells/ProfileTableViewCell.swift
  Noonbody/Noonbody/Source/Presentation/Preferences/ViewControllers/ProfileViewController.swift
  Noonbody/Noonbody/Source/Presentation/Utils/UserManager.swift
Labels: 🚨 bug
