Repository depromeet/everyBody-iOS, pull requests merged in 2022-01, with the labels that each got.

#76 [#75] release 환경에서 configuration 파일을 읽어올 수 있도록 설정
  Noonbody/Noonbody.xcodeproj/project.pbxproj
  Noonbody/Noonbody/GoogleService-Info.plist
  Noonbody/Noonbody/Resource/Support/Info.plist
  Noonbody/Noonbody/Source/Scene/Home/ViewControllers/HomeViewController.swift
Labels: 💭 yezl, 🚨 bug

#77 #72: 엠티 뷰에서 버튼 숨김 + 사진 전체 삭제 버그 픽스
  Noonbody/Noonbody/Source/Scene/Panorama/Extensions/PanoramaViewController+Extensions.swift
  Noonbody/Noonbody/Source/Scene/Panorama/ViewControllers/PanoramaViewController.swift
Labels: 🎈 yukyung, 🚨 bug

#78 #74: panorama view server
  Noonbody/Noonbody.xcodeproj/project.pbxproj
  Noonbody/Noonbody/Source/Network/Panorama/PanoramaAPI.swift
  Noonbody/Noonbody/Source/Network/Panorama/PanoramaService.swift
  Noonbody/Noonbody/Source/Scene/Home/ViewControllers/HomeViewController.swift
  Noonbody/Noonbody/Source/Scene/Panorama/Repository/PanoramaRepository.swift
  Noonbody/Noonbody/Source/Scene/Panorama/UseCase/PanoramaUseCase.swift
  Noonbody/Noonbody/Source/Scene/Panorama/ViewControllers/PanoramaViewController.swift
  Noonbody/Noonbody/Source/Scene/Panorama/ViewModels/PanoramaViewModel.swift
Labels: 🎈 yukyung, 🏅 feat

#80 [#79] 앨범에서 사진 가져오기
  Noonbody/Noonbody.xcodeproj/project.pbxproj
  Noonbody/Noonbody/Source/Scene/Camera/Model/Camera.swift
  Noonbody/Noonbody/Source/Scene/Camera/Model/ViewFinder.swift
  Noonbody/Noonbody/Source/Scene/Camera/ViewControllers/CameraOutputViewController.swift
  Noonbody/Noonbody/Source/Scene/Camera/ViewControllers/CameraViewController.swift
  Noonbody/Noonbody/Source/Scene/Camera/ViewModels/CameraViewModel.swift
  Noonbody/Noonbody/Source/Scene/Camera/ViewModels/PoseViewModel.swift
  Noonbody/Noonbody/Source/Scene/Camera/Views/BottomSheetView.swift
Labels: 💭 yezl, 🏅 feat

#85 #72: 파라노마 카메라 셀에 뷰 연결 + 내비게이션 초기화 수정 + 오타 수정
  Noonbody/Noonbody/Source/Presentation/Home/ViewControllers/HomeViewController.swift
  Noonbody/Noonbody/Source/Presentation/Home/ViewModels/AlbumViewModel.swift
  Noonbody/Noonbody/Source/Presentation/Panorama/Cells/CameraCollectionViewCell.swift
  Noonbody/Noonbody/Source/Presentation/Panorama/Extensions/PanoramaViewController+Extensions.swift
  Noonbody/Noonbody/Source/Presentation/Panorama/ViewControllers/PanoramaViewController.swift
  Noonbody/Noonbody/Source/Presentation/Panorama/ViewModels/PanoramaViewModel.swift
Labels: 🎈 yukyung, 🏅 feat, 🚨 bug

#87 #84: 앱 스위치 상태 저장 및 앱 설정 변경
  .gitignore
  Noonbody/Noonbody.xcodeproj/project.pbxproj
  Noonbody/Noonbody/GoogleService-Info.plist
  Noonbody/Noonbody/Resource/Constants/UserDefaultKey.swift
  Noonbody/Noonbody/Resource/Support/AppDelegate.swift
  Noonbody/Noonbody/Source/Data/Network/Auth/AuthAPI.swift
  Noonbody/Noonbody/Source/Data/Network/Utils/BaseTargetType.swift
  Noonbody/Noonbody/Source/Domain/Entity/SignInRequestModel.swift
  Noonbody/Noonbody/Source/Presentation/Camera/ViewControllers/CameraOutputViewController.swift
  Noonbody/Noonbody/Source/Presentation/Camera/ViewControllers/CameraViewController.swift
  Noonbody/Noonbody/Source/Presentation/Camera/Views/CustomSwitch.swift
  Noonbody/Noonbody/Source/Presentation/Home/ViewControllers/HomeViewController.swift
  Noonbody/Noonbody/Source/Presentation/Launch/ViewController/LaunchScreenViewController.swift
  Noonbody/Noonbody/Source/Presentation/Preferences/Cells/ProfileTableViewCell.swift
  Noonbody/Noonbody/Source/Presentation/Preferences/ViewControllers/NotificationViewController.swift
  Noonbody/Noonbody/Source/Presentation/Preferences/ViewControllers/ProfileViewController.swift
  Noonbody/Noonbody/Source/Presentation/Preferences/ViewModel/ProfileViewModel.swift
  Noonbody/Noonbody/Source/Presentation/Utils/UserDefault.swift
  Noonbody/Noonbody/Source/Presentation/Utils/UserManager.swift
Labels: 💭 yezl, 🏅 feat, ✏️ refactor

#96 #91: 카메라 접근 권한 거부 시 팝업 안내 문구
  Noonbody/Noonbody/Source/Presentation/Camera/ViewControllers/CameraViewController.swift
  Noonbody/Noonbody/Source/Presentation/Utils/PopUpViewController.swift
Labels: 💭 yezl, 🏅 feat

#95 #90 : panorama selected bug
  Noonbody/Noonbody/Source/Presentation/Panorama/Cells/BottomCollectionViewCell.swift
  Noonbody/Noonbody/Source/Presentation/Panorama/Extensions/PanoramaViewController+Extensions.swift
  Noonbody/Noonbody/Source/Presentation/Panorama/ViewControllers/PanoramaViewController.swift
Labels: 🎈 yukyung, 🚨 bug

#103 [non_issue] 누락된 로티 파일 추가
  Noonbody/Noonbody.xcodeproj/project.pbxproj
  Noonbody/Noonbody/Resource/Lottie/loading.json
Labels: 🏅 feat, 🧸 chore

#100 #99: 삭제 시 전체 앨범 데이터에서도 삭제 / 팝업 취소 시 배열 초기화
  Noonbody/Noonbody.xcodeproj/project.pbxproj
  Noonbody/Noonbody.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Noonbody/Noonbody/Source/Presentation/Panorama/ViewControllers/PanoramaViewController.swift
Labels: 🎈 yukyung, 🚨 bug

#102 #97: 동영상 저장 뷰 레이아웃
  Noonbody/Noonbody.xcodeproj/project.pbxproj
  Noonbody/Noonbody/Resource/Constants/Assets+Generated.swift
  Noonbody/Noonbody/Resource/Image.xcassets/Close.imageset/Close.png
  Noonbody/Noonbody/Resource/Image.xcassets/Close.imageset/Close@2x.png
  Noonbody/Noonbody/Resource/Image.xcassets/Close.imageset/Close@3x.png
  Noonbody/Noonbody/Resource/Image.xcassets/Close.imageset/Contents.json
  Noonbody/Noonbody/Resource/Image.xcassets/ShareWhite.imageset/Contents.json
  Noonbody/Noonbody/Resource/Image.xcassets/ShareWhite.imageset/ShareWhite.png
  Noonbody/Noonbody/Resource/Image.xcassets/ShareWhite.imageset/ShareWhite@2x.png
  Noonbody/Noonbody/Resource/Image.xcassets/ShareWhite.imageset/ShareWhite@3x.png
  Noonbody/Noonbody/Resource/Image.xcassets/selectedClose.imageset/Contents.json
  Noonbody/Noonbody/Resource/Image.xcassets/selectedClose.imageset/selectedClose.png
  Noonbody/Noonbody/Resource/Image.xcassets/selectedClose.imageset/selectedClose@2x.png
  Noonbody/Noonbody/Resource/Image.xcassets/selectedClose.imageset/selectedClose@3x.png
  Noonbody/Noonbody/Source/Presentation/Panorama/ViewControllers/PanoramaViewController.swift
  Noonbody/Noonbody/Source/Presentation/Utils/UINavigationController+Extensions.swift
  Noonbody/Noonbody/Source/Presentation/Video/Cell/PreviewCollectionViewCell.swift
  Noonbody/Noonbody/Source/Presentation/Video/ViewController/VideoEditViewController.swift
Labels: 💭 yezl, 🏅 feat

#108 #104: 동영상 서버 연결
  Noonbody/Noonbody.xcodeproj/project.pbxproj
  Noonbody/Noonbody.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Noonbody/Noonbody/Resource/Support/Info.plist
  Noonbody/Noonbody/Source/Data/Network/Utils/HTTPMethodURL.swift
  Noonbody/Noonbody/Source/Data/Network/Video/VideoAPI.swift
  Noonbody/Noonbody/Source/Data/Network/Video/VideoService.swift
  Noonbody/Noonbody/Source/Data/Repositories/DefaultVideoRepository.swift
  Noonbody/Noonbody/Source/Domain/Entity/VideoRequestModel.swift
  Noonbody/Noonbody/Source/Domain/Interfaces/Repositories/VideoRepository.swift
  Noonbody/Noonbody/Source/Domain/UseCases/VideoUseCase.swift
  Noonbody/Noonbody/Source/Presentation/Utils/Rx+PreviewCollectionViewCell.swift
  Noonbody/Noonbody/Source/Presentation/Video/Cell/PreviewCollectionViewCell.swift
  Noonbody/Noonbody/Source/Presentation/Video/ViewController/VideoEditViewController.swift
  Noonbody/Noonbody/Source/Presentation/Video/ViewModel/VideoViewModel.swift
Labels: 💭 yezl, 🏅 feat

#115 #111: 동영상 저장 뷰에서 삭제해도 ImageList 갱신되지 않는 버그 픽스
  Noonbody/Noonbody/Source/Presentation/Video/ViewController/VideoEditViewController.swift
  Noonbody/Noonbody/Source/Presentation/Video/ViewModel/VideoViewModel.swift
Labels: 💭 yezl, 🚨 bug

#113 #105: 앨범 수정, 삭제 뷰
  Noonbody/Noonbody.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Noonbody/Noonbody/Resource/Color.xcassets/Red.colorset/Contents.json
  Noonbody/Noonbody/Resource/Constants/Assets+Generated.swift
  Noonbody/Noonbody/Resource/Image.xcassets/DelGray.imageset/Contents.json
  Noonbody/Noonbody/Resource/Image.xcassets/DelGray.imageset/DelGray.png
  Noonbody/Noonbody/Resource/Image.xcassets/DelGray.imageset/DelGray@2x.png
  Noonbody/Noonbody/Resource/Image.xcassets/DelGray.imageset/DelGray@3x.png
  Noonbody/Noonbody/Resource/Image.xcassets/ShareGray.imageset/Contents.json
  Noonbody/Noonbody/Resource/Image.xcassets/ShareGray.imageset/ShareGray.png
  Noonbody/Noonbody/Resource/Image.xcassets/ShareGray.imageset/ShareGray@2x.png
  Noonbody/Noonbody/Resource/Image.xcassets/ShareGray.imageset/ShareGray@3x.png
  Noonbody/Noonbody/Resource/Image.xcassets/folder_open.imageset/Contents.json
  Noonbody/Noonbody/Resource/Image.xcassets/folder_open.imageset/folder_open.png
  Noonbody/Noonbody/Resource/Image.xcassets/folder_open.imageset/folder_open@2x.png
  Noonbody/Noonbody/Resource/Image.xcassets/folder_open.imageset/folder_open@3x.png
  Noonbody/Noonbody/Resource/Image.xcassets/option.imageset/Contents.json
  Noonbody/Noonbody/Resource/Image.xcassets/option.imageset/option.png
  Noonbody/Noonbody/Resource/Image.xcassets/option.imageset/option@2x.png
  Noonbody/Noonbody/Resource/Image.xcassets/option.imageset/option@3x.png
  Noonbody/Noonbody/Source/Presentation/Panorama/ViewControllers/PanoramaViewController.swift
  Noonbody/Noonbody/Source/Presentation/Utils/PopUpViewController.swift
  Noonbody/Noonbody/Source/Presentation/Utils/UINavigationController+Extensions.swift
  Noonbody/Noonbody/Source/Presentation/Utils/UINavigationItem+Extensions.swift
Labels: 🎈 yukyung, 🏅 feat

#116 #112: 앱에만 저장하기 로직 수정
  Noonbody/Noonbody/Source/Presentation/Preferences/Cells/ProfileTableViewCell.swift
  Noonbody/Noonbody/Source/Presentation/Preferences/ViewControllers/ProfileViewController.swift
Labels: 💭 yezl, 🚨 bug

#119 #106: 앨범 수정, 삭제 서버 연결 / 팝업 뷰컨 폰트 크기, 버튼 색상 수정
  Noonbody/Noonbody.xcodeproj/project.pbxproj
  Noonbody/Noonbody/Source/Data/Network/CreateAlbum/CreateAlbumAPI.swift
  Noonbody/Noonbody/Source/Data/Network/CreateAlbum/CreateAlbumService.swift
  Noonbody/Noonbody/Source/Data/Network/Panorama/PanoramaAPI.swift
  Noonbody/Noonbody/Source/Data/Network/Panorama/PanoramaService.swift
  Noonbody/Noonbody/Source/Data/Network/Utils/HTTPMethodURL.swift
  Noonbody/Noonbody/Source/Data/Repositories/DefaultAlbumRepositry.swift
  Noonbody/Noonbody/Source/Data/Repositories/DefaultPanoramaRepository.swift
  Noonbody/Noonbody/Source/Domain/Entity/AlbumRequestModel.swift
  Noonbody/Noonbody/Source/Domain/Entity/CreateAlbumRequestModel.swift
  Noonbody/Noonbody/Source/Domain/Interfaces/Repositories/AlbumRepository.swift
  Noonbody/Noonbody/Source/Domain/UseCases/AlbumUseCase.swift
  Noonbody/Noonbody/Source/Domain/UseCases/PanoramaUseCase.swift
  Noonbody/Noonbody/Source/Presentation/Camera/ViewModels/AlbumSelectionViewModel.swift
  Noonbody/Noonbody/Source/Presentation/Home/ViewModels/AlbumCreationViewModel.swift
  Noonbody/Noonbody/Source/Presentation/Panorama/Model/RenamedAlbum.swift
  Noonbody/Noonbody/Source/Presentation/Panorama/ViewControllers/PanoramaViewController.swift
  Noonbody/Noonbody/Source/Presentation/Panorama/ViewModels/PanoramaViewModel.swift
  Noonbody/Noonbody/Source/Presentation/Utils/PopUpViewController.swift
Labels: 🎈 yukyung, 🏅 feat

#121 #120: 홈 화면 스켈레톤 적용
  Noonbody/Noonbody.xcodeproj/project.pbxproj
  Noonbody/Noonbody.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Noonbody/Noonbody/Source/Presentation/Component/AlbumCollectionViewCell.swift
  Noonbody/Noonbody/Source/Presentation/Home/ViewControllers/HomeViewController.swift
  Noonbody/Noonbody/Source/Presentation/Utils/UIImageView+setImage.swift
Labels: 💭 yezl, 🏅 feat

#124 #122: 개인정보 처리방침 추가
  Noonbody/Noonbody.xcodeproj/project.pbxproj
  Noonbody/Noonbody/Source/Presentation/Preferences/Data/ProfileDataType.swift
  Noonbody/Noonbody/Source/Presentation/Preferences/ViewControllers/PrivacyPolicyViewController.swift
  Noonbody/Noonbody/Source/Presentation/Preferences/ViewControllers/ProfileViewController.swift
  Noonbody/Noonbody/Source/Presentation/Preferences/ViewModel/ProfileViewModel.swift
Labels: 💭 yezl, 🏅 feat

#127 #123: 팝업 시스템 레이아웃 수정
  Noonbody/Noonbody.xcodeproj/project.pbxproj
  Noonbody/Noonbody.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Noonbody/Noonbody/Resource/Font/Fonts.swift
  Noonbody/Noonbody/Source/Data/Network/Utils/BaseTargetType.swift
  Noonbody/Noonbody/Source/Presentation/Camera/ViewControllers/AlbumSelectionViewController.swift
  Noonbody/Noonbody/Source/Presentation/Launch/LaunchService.swift
  Noonbody/Noonbody/Source/Presentation/Panorama/ViewControllers/PanoramaViewController.swift
  Noonbody/Noonbody/Source/Presentation/Utils/PopUpViewController.swift
  Noonbody/Noonbody/Source/Presentation/Utils/Rx+PreviewCollectionViewCell.swift
  Noonbody/Noonbody/Source/Presentation/Utils/UILabel+setLineHeight.swift
  Noonbody/Noonbody/Source/Presentation/Video/View/CircleProgressView.swift
Labels: 💭 yezl, 🧸 chore, 🪄 style

#131 #130: 삭제 후 팝업이 사라지지 않는 버그
  Noonbody/Noonbody/Source/Presentation/Panorama/ViewControllers/PanoramaViewController.swift
Labels: 🎈 yukyung, 🚨 bug

#134 #133: share sheet 활용하여 공유 기능 추가
  Noonbody/Noonbody/Source/Presentation/Preferences/ViewControllers/NotificationViewController.swift
  Noonbody/Noonbody/Source/Presentation/Utils/PopUpViewController.swift
  Noonbody/Noonbody/Source/Presentation/Video/ViewController/VideoEditViewController.swift
Labels: 💭 yezl, 🏅 feat

#136 #125: 피드백 창구 뷰 추가
  Noonbody/Noonbody.xcodeproj/project.pbxproj
  Noonbody/Noonbody/Resource/Constants/Assets+Generated.swift
  Noonbody/Noonbody/Resource/Image.xcassets/next.imageset/Contents.json
  Noonbody/Noonbody/Resource/Image.xcassets/next.imageset/next.png
  Noonbody/Noonbody/Resource/Image.xcassets/next.imageset/next@2x.png
  Noonbody/Noonbody/Resource/Image.xcassets/next.imageset/next@3x.png
  Noonbody/Noonbody/Source/Presentation/Component/NBCircleButton.swift
  Noonbody/Noonbody/Source/Presentation/Home/Cells/FeedBackCollectionReusableView.swift
  Noonbody/Noonbody/Source/Presentation/Home/ViewControllers/FeedBackPopUpViewController.swift
  Noonbody/Noonbody/Source/Presentation/Home/ViewControllers/HomeViewController.swift
  Noonbody/Noonbody/Source/Presentation/Preferences/ViewControllers/NotificationViewController.swift
  Noonbody/Noonbody/Source/Presentation/Utils/UICollectionView+Generic.swift
Labels: 🎈 yukyung, 🏅 feat

#135 #114: 파노라마 버그 픽스
  Noonbody/Noonbody.xcodeproj/project.pbxproj
  Noonbody/Noonbody/Source/Data/Network/Album/AlbumAPI.swift
  Noonbody/Noonbody/Source/Data/Network/Album/AlbumService.swift
  Noonbody/Noonbody/Source/Data/Network/Panorama/PanoramaAPI.swift
  Noonbody/Noonbody/Source/Data/Network/Panorama/PanoramaService.swift
  Noonbody/Noonbody/Source/Data/Repositories/DefaultAlbumRepositry.swift
  Noonbody/Noonbody/Source/Data/Repositories/DefaultPanoramaRepository.swift
  Noonbody/Noonbody/Source/Domain/Interfaces/Repositories/AlbumRepository.swift
  Noonbody/Noonbody/Source/Domain/Interfaces/Repositories/PanoramaRepository.swift
  Noonbody/Noonbody/Source/Domain/UseCases/AlbumUseCase.swift
  Noonbody/Noonbody/Source/Domain/UseCases/PanoramaUseCase.swift
  Noonbody/Noonbody/Source/Presentation/Panorama/Extensions/PanoramaViewController+Extensions.swift
  Noonbody/Noonbody/Source/Presentation/Panorama/ViewControllers/PanoramaViewController.swift
  Noonbody/Noonbody/Source/Presentation/Panorama/ViewModels/PanoramaViewModel.swift
  Noonbody/Noonbody/Source/Presentation/Utils/Rx+ViewLifeCycle.swift
Labels: 🎈 yukyung, 🚨 bug
